// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
// SPDX-License-Identifier: Apache-2.0
//
// Types générés depuis internal/api via `make web-types` (tygo).
// Ne pas modifier à la main.

//////////
// source: api.go
/*
Package api expose les endpoints REST + SSE qui alimentent
l'interface web embarquée. Découplé du paquet PayZen dans le sens
où il ne connaît QUE le store payzen et la queue delivery (sources
de vérité) — pas la logique métier.

Toutes les routes sont montées sous /paysim/api/v1/*. Protection
Bearer optionnelle via PAYSIM_API_TOKEN (identique au reste des
endpoints /paysim/*).
*/

/**
 * Deps regroupe les dépendances de l'API UI. Struct plutôt que
 * paramètres positionnels — plus lisible et extensible sans
 * breaking change côté cmd/paysim.
 * SubscriptionRepo et PaymentMethodRepo sont optionnels — nil en
 * mode mémoire, les endpoints listing correspondants retournent alors
 * une liste vide (comportement cohérent avec le mode dégradé mémoire :
 * les entités survivent au run mais ne sont pas listées globalement).
 */
export interface Deps {
  Store: any /* payzen.Store */;
  PaymentRepo: any /* store.PaymentRepository */; // optionnel — nil en mode mémoire ; permet les endpoints DELETE cross-provider
  SubscriptionRepo: any /* store.SubscriptionRepository */; // optionnel — mode SQLite uniquement pour listing global
  PaymentMethodRepo: any /* store.PaymentMethodRepository */; // optionnel — mode SQLite uniquement
  Queue?: any /* delivery.Queue */;
  Publisher?: any /* bus.Bus */;
  Logger?: any /* slog.Logger */;
  Token: string; // Bearer requis si non vide, sinon API ouverte
  PayzenHandler?: any /* payzen.Handler */;
}
/**
 * Handler regroupe les dépendances nécessaires pour servir les
 * endpoints API et SSE. Instancié dans cmd/paysim/main.go.
 */
export interface Handler {
}
/**
 * PaymentSummary est le résumé d'un paiement pour les listes.
 */
export interface PaymentSummary {
  uuid: string;
  provider: string;
  orderId: string;
  amount: number /* int64 */;
  currency: string;
  state: string;
  createdAt: string /* RFC 3339 */;
  updatedAt: string /* RFC 3339 */;
}
/**
 * PaymentDetail ajoute le journal d'événements.
 */
export interface PaymentDetail {
  PaymentSummary: PaymentSummary;
  events: EventEntry[];
}
/**
 * EventEntry est une entrée du journal d'événements du domaine.
 */
export interface EventEntry {
  at: string /* RFC 3339 */;
  kind: string;
  amount?: number /* int64 */;
  note?: string;
}
/**
 * WebhookEntry résume une tentative de livraison — pour la liste UI.
 */
export interface WebhookEntry {
  id: string;
  url: string;
  /**
   * Status décrit l'acheminement HTTP ("delivered", "failed",
   * "pending"), Outcome le résultat métier annoncé dans le corps
   * ("PAID", "UNPAID"… en vocabulaire provider). Deux questions
   * distinctes : un webhook peut être remis avec succès tout en
   * annonçant un refus.
   */
  status: string;
  outcome?: string;
  statusCode?: number /* int */;
  errorMsg?: string;
  attempts: number /* int */;
  createdAt: string /* RFC 3339 */;
  completedAt: string /* RFC 3339 */;
}
/**
 * WebhookDetail ajoute les headers et le body pour la vue
 * requête/réponse côte à côte.
 */
export interface WebhookDetail {
  WebhookEntry: WebhookEntry;
  headers: { [key: string]: string};
  body: string;
}
/**
 * CreatePaymentInput est le corps de POST /paysim/api/v1/payments,
 * endpoint générique de création cross-provider. Le champ Provider
 * choisit l'adaptateur qui matérialise le paiement (seul "payzen"
 * est câblé aujourd'hui ; Stripe arrivera en phase 5). Vide = payzen
 * par défaut pour ne pas alourdir les scénarios monoprovider.
 * FormAction, NotificationURL, Card et PaymentMethodToken ouvrent le
 * support des paiements récurrents (4.4.5) :
 *   - FormAction=REGISTER_PAY|ASK_REGISTER_PAY + Card : enregistre le
 *     moyen de paiement à l'issue, retourne un paymentMethodToken.
 *   - PaymentMethodToken sans Card : rejeu one-click à partir du moyen
 *     stocké — capture directe, webhook émis (si NotificationURL et
 *     token de la boutique configurés côté serveur).
 */
export interface CreatePaymentInput {
  provider?: string;
  amount: any /* format.Amount */;
  currency: string;
  orderId: string;
  formAction?: string;
  customer?: any /* payzen.Customer */;
  metadata?: { [key: string]: string};
  notificationUrl?: string;
  card?: any /* payzen.Card */;
  paymentMethodToken?: string;
}
/**
 * CreatePaymentOutput retourne l'uuid attribué au paiement et son
 * état à l'issue de l'appel. PaymentMethodToken est renseigné dans
 * deux cas :
 *   - après un enrôlement (Card + FormAction REGISTER_PAY),
 *   - après un rejeu one-click (echo du token utilisé).
 * Le marchand n'a pas besoin de GET juste après pour lire l'état,
 * State est présent dans la réponse même en cas de rejeu (où l'état
 * devient captured ou declined dès le retour HTTP).
 */
export interface CreatePaymentOutput {
  uuid: string;
  provider: string;
  state: string;
  paymentMethodToken?: string;
}
/**
 * SimulatePaymentRequest est le corps de POST
 * /paysim/api/v1/payments/{uuid}/simulate. L'UI n'a pas à connaître
 * le formToken interne — Paysim le retrouve depuis l'uuid. Le champ
 * channel choisit entre retour navigateur (défaut) et IPN pur.
 */
export interface SimulatePaymentRequest {
  outcome: string; // PAID | AUTHORISED | UNPAID | EXPIRED | ABANDONED
  channel?: string; // "browserReturn" (défaut) | "ipn"
  returnUrl?: string;
  notificationUrl?: string;
  cardBrand?: string;
  threeDSStatus?: string;
  errorCode?: string;
  errorMessage?: string;
  /**
   * Chaos active des modes de panne sur le webhook émis par cet
   * appel — chaque flag indépendant, tous inertes par défaut. Ces
   * modes sont ceux qui n'ont pas de sens côté REST V4 native mais
   * sont critiques pour tester la robustesse d'un intégrateur :
   * duplicate (double envoi), badSignature (kr-hash altéré),
   * raceBeforeResponse (webhook part avant le retour HTTP).
   */
  chaos?: any /* payzen.WebhookChaos */;
  /**
   * DeliveryDelayMs retarde l'envoi du webhook (millisecondes).
   * Compose avec deux appels successifs pour simuler du out-of-order
   * sans flag dédié.
   */
  deliveryDelayMs?: number /* int */;
}
/**
 * SimulatePaymentResponse retourne le deliveryId et le hash calculé.
 */
export interface SimulatePaymentResponse {
  deliveryId: string;
  krHash: string;
  channel: string;
}
/**
 * ReplayWebhookResponse retourne l'identifiant du nouveau webhook
 * enqueue. L'original reste dans l'historique — le rejeu est une
 * nouvelle tentative distincte.
 */
export interface ReplayWebhookResponse {
  newDeliveryId: string;
}
/**
 * CreateSubscriptionInput est le corps de POST /paysim/api/v1/subscriptions,
 * endpoint générique cross-provider pour créer un abonnement. Le champ
 * Provider distingue l'adaptateur (payzen par défaut). PaymentMethodToken
 * doit correspondre à un moyen de paiement précédemment enregistré via
 * POST /paysim/api/v1/payments avec Card.
 * EffectDate et Rrule reprennent le vocabulaire PayZen / iCalendar
 * (RFC 5545) — recopiés tels quels, cf. providers.md.
 */
export interface CreateSubscriptionInput {
  provider?: string;
  paymentMethodToken: string;
  amount: any /* format.Amount */;
  currency: string;
  orderId?: string;
  effectDate?: string;
  rrule?: string;
  metadata?: { [key: string]: string};
}
/**
 * SubscriptionOutput est la vue exposée d'un abonnement. Cancelled
 * remonte pour que le marchand puisse le voir sans recharger.
 */
export interface SubscriptionOutput {
  id: string;
  provider: string;
  paymentMethodToken: string;
  amount: any /* format.Amount */;
  currency: string;
  orderId?: string;
  effectDate?: string;
  rrule?: string;
  metadata?: { [key: string]: string};
  cancelled: boolean;
  createdAt: string /* RFC 3339 */;
}
/**
 * TriggerBillingOutput retourne l'identifiant du paiement créé par
 * le trigger d'échéance. L'appelant peut ensuite GET /payments/{uuid}
 * pour lire l'état complet et la trace du domaine.
 */
export interface TriggerBillingOutput {
  subscriptionId: string;
  paymentUuid: string;
  state: string;
}
/**
 * PaymentMethodOutput est la vue exposée d'un moyen de paiement
 * enregistré. PANFull volontairement absent — le simulateur stocke en
 * clair, mais l'API l'expose sous forme masquée uniquement (comme un
 * vrai PSP dans son back-office).
 */
export interface PaymentMethodOutput {
  token: string;
  provider: string;
  panMasked: string;
  brand?: string;
  holderName?: string;
  expiryMonth: number /* int */;
  expiryYear: number /* int */;
  /**
   * Caractérisation émetteur, telle qu'enrôlée. Absentes du JSON
   * quand l'enrôlement ne les a pas fournies — l'API ne réaffirme
   * pas les défauts appliqués au rendu du kr-answer.
   */
  country?: string;
  productCategory?: string;
  issuerName?: string;
  revoked: boolean;
  createdAt: string /* RFC 3339 */;
  /**
   * Usable dit si ce moyen peut encore produire un paiement accepté,
   * UnusableReason pourquoi il ne le peut pas. Dérivés à la lecture,
   * jamais stockés : les trois causes — révocation, expiration, PAN
   * de refus — se déduisent de ce qui est déjà là, et un champ figé
   * deviendrait faux au premier changement de mois.
   * Sans eux, une carte que tout débit refusera est indistinguable
   * d'une carte valide dans la collection. Le simulateur ment alors
   * sur ses propres données, ce qui est plus coûteux qu'une absence
   * d'information.
   */
  usable: boolean;
  unusableReason?: string;
}
