// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
// SPDX-License-Identifier: Apache-2.0
//
// Types générés depuis internal/api via `make web-types` (tygo).
// Ne pas modifier à la main.

//////////
// source: api.go
/*
Package api expose les endpoints REST + SSE qui alimentent
l'interface web embarquée. Découplé du paquet PayZen dans le sens
où il ne connaît QUE le store payzen et la queue delivery (sources
de vérité) — pas la logique métier.

Toutes les routes sont montées sous /paysim/api/v1/*. Protection
Bearer optionnelle via PAYSIM_API_TOKEN (identique au reste des
endpoints /paysim/*).
*/

/**
 * Deps regroupe les dépendances de l'API UI. Struct plutôt que
 * 6 paramètres positionnels — plus lisible et extensible sans
 * breaking change côté cmd/paysim.
 */
export interface Deps {
  Store: any /* payzen.Store */;
  PaymentRepo: any /* store.PaymentRepository */; // optionnel — nil en mode mémoire ; permet les endpoints DELETE cross-provider
  Queue?: any /* delivery.Queue */;
  Publisher?: any /* bus.Bus */;
  Logger?: any /* slog.Logger */;
  Token: string; // Bearer requis si non vide, sinon API ouverte
  PayzenHandler?: any /* payzen.Handler */;
}
/**
 * Handler regroupe les dépendances nécessaires pour servir les
 * endpoints API et SSE. Instancié dans cmd/paysim/main.go.
 */
export interface Handler {
}
/**
 * PaymentSummary est le résumé d'un paiement pour les listes.
 */
export interface PaymentSummary {
  uuid: string;
  provider: string;
  orderId: string;
  amount: number /* int64 */;
  currency: string;
  state: string;
  createdAt: string /* RFC 3339 */;
  updatedAt: string /* RFC 3339 */;
}
/**
 * PaymentDetail ajoute le journal d'événements.
 */
export interface PaymentDetail {
  PaymentSummary: PaymentSummary;
  events: EventEntry[];
}
/**
 * EventEntry est une entrée du journal d'événements du domaine.
 */
export interface EventEntry {
  at: string /* RFC 3339 */;
  kind: string;
  amount?: number /* int64 */;
  note?: string;
}
/**
 * WebhookEntry résume une tentative de livraison — pour la liste UI.
 */
export interface WebhookEntry {
  id: string;
  url: string;
  status: string;
  statusCode?: number /* int */;
  errorMsg?: string;
  attempts: number /* int */;
  createdAt: string /* RFC 3339 */;
  completedAt: string /* RFC 3339 */;
}
/**
 * WebhookDetail ajoute les headers et le body pour la vue
 * requête/réponse côte à côte.
 */
export interface WebhookDetail {
  WebhookEntry: WebhookEntry;
  headers: { [key: string]: string};
  body: string;
}
/**
 * SimulatePaymentRequest est le corps de POST
 * /paysim/api/v1/payments/{uuid}/simulate. L'UI n'a pas à connaître
 * le formToken interne — Paysim le retrouve depuis l'uuid. Le champ
 * channel choisit entre retour navigateur (défaut) et IPN pur.
 */
export interface SimulatePaymentRequest {
  outcome: string; // PAID | AUTHORISED | UNPAID | EXPIRED | ABANDONED
  channel?: string; // "browserReturn" (défaut) | "ipn"
  returnUrl?: string;
  notificationUrl?: string;
  cardBrand?: string;
  threeDSStatus?: string;
  errorCode?: string;
  errorMessage?: string;
}
/**
 * SimulatePaymentResponse retourne le deliveryId et le hash calculé.
 */
export interface SimulatePaymentResponse {
  deliveryId: string;
  krHash: string;
  channel: string;
}
/**
 * ReplayWebhookResponse retourne l'identifiant du nouveau webhook
 * enqueue. L'original reste dans l'historique — le rejeu est une
 * nouvelle tentative distincte.
 */
export interface ReplayWebhookResponse {
  newDeliveryId: string;
}
